/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUSOP = 4;
  /** RegularExpression Id. */
  int MINUSOP = 5;
  /** RegularExpression Id. */
  int MULOP = 6;
  /** RegularExpression Id. */
  int DIVOP = 7;
  /** RegularExpression Id. */
  int OPEN = 8;
  /** RegularExpression Id. */
  int CLOSE = 9;
  /** RegularExpression Id. */
  int EQOP = 10;
  /** RegularExpression Id. */
  int MINUSSIGN = 11;
  /** RegularExpression Id. */
  int DOT = 12;
  /** RegularExpression Id. */
  int NUM = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"#\"",
    "\".\"",
    "<NUM>",
  };

}
